export interface EventSummary {
    _id : String,
    eventid : String,
    month : String,
    baselocation : String,
    beneficiaryname : String,
    venueaddress : String,
    councilname : String,
    project : String,
    category : String,
    eventname : String,
    eventdesc : String,
    eventdate : Date,
    totalnoofvolunteers : Number,
    totalnoofvolunteerhours : Number,
    totalnooftravelhours : Number,
    overallvolunteeringhrs :Number,
    livesimpacted : Number,
    activitytype : String,
    status : String,
    pocid : String,
    pocname : String,
    poccontactnumber : String
}